version: "3.7"

services:
    zookeeper:
        image: "wurstmeister/zookeeper:latest"
        ports:
            - "2181:2181"

    kafka:
        image: "wurstmeister/kafka:2.11-1.1.1"
        ports:
            - "9092:9092"
        depends_on:
            - "zookeeper"
        environment:
            KAFKA_CREATE_TOPICS: "user_names:4:1,users_scraped:4:1,posts_scraped:4:1"
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_ADVERTISED_HOST_NAME: "localhost"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
