version: "3.2"
services:
  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:0.10.2.0"
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_CREATE_TOPICS: "user_names:4:1,user_follow_infos:4:1,user_scrape_errors:1:1,reached_limit:4:1,renewed_elastic_ip:4:1,renewing_elastic_ip_errors:4:1,user_post:4:1,user_instagram-scrape_errors:4:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:11.5
    ports:
      - 5432:5432

volumes:
  dgraph:
